### PR TITLE
Fix decoding i8/i16 by using DataView and preventing future false use of `u8aToNumber` by deprecating it

### PR DESCRIPTION
**Pull request by peetzweg**
change decoding of byte to number methods for numbers <=32 bits, furthermore limiting to use i8/16/32

using DataView api do implement simpler decoding of these fixed width numbers. Thereby deprecating `u8aToNumber()`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView

Needed for https://github.com/polkadot-js/api/issues/5702 and https://github.com/polkadot-js/api/pull/5703

See https://github.com/polkadot-js/api/pull/5703#issuecomment-1684059771 for what was wrong with the previous implementation.

### CODE REVIEW

**Comment by peetzweg** [comment]
Could change the implementation of `toBN` similar to this. Let me know what you think @jacogr , haven't check the performance implication compared to the previous implementation yet. 🙈 

https://github.com/polkadot-js/common/blob/master/packages/util/src/u8a/toBn.ts


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getBigInt64

**Comment by jacogr** [comment]
`u8aToNumber` is specifically there for performance as a shortcut path for smaller numbers.

DataView is much slower, doing so is a regression. (We've been there...)

**Comment by jacogr** [comment]
Ok, so the `isNegative` branch is the issue. What is does wrong (for each of `u8aTo{BigInt, Bn, Number}` -

It _always_ does the negative conversion, i.e. `(value * -1) -1` - this should _only_ apply when the input value is negative, i.e. when the top-most bit is set. Hence you would probably see that negative values are ok, but positive values (where the bit is not set) always ends up negative.

**Comment by jacogr** [comment]
Sorry, another ramble, should have edited somewhere above. For perf tests -

Run `yarn test --console u8a/toBigInt u8a/toBn u8a/toNumber` (aka test with the `--console` flag and the specific files)

Output of the performance-related logs for me -

```
packages/util/src/u8a/toBigInt.spec.ts::

	
	performance run for u8aToBigInt (i32) completed with 750,000 iterations.
	
	              u8aToBigInt (i32):            32.60 ms
	                                    23,009,134.73 ops/s
	                                             0.04 μs/op
	
	
	performance run for u8aToBigInt (u32) completed with 750,000 iterations.
	
	              u8aToBigInt (u32):            29.14 ms
	                                    25,734,984.69 ops/s
	                                             0.04 μs/op
	
	
	performance run for u8aToBigInt (u64) completed with 750,000 iterations.
	
	              u8aToBigInt (u64):            69.44 ms
	                                    10,799,913.65 ops/s
	                                             0.09 μs/op
	
	
	performance run for u8aToBigInt (u128) completed with 750,000 iterations.
	
	             u8aToBigInt (u128):            97.43 ms
	                                     7,697,982.53 ops/s
	                                             0.13 μs/op
	

packages/util/src/u8a/toBn.spec.ts::

	
	performance run for u8aToBn (i32) completed with 750,000 iterations.
	
	                  u8aToBn (i32):            28.01 ms
	                                    26,776,988.09 ops/s
	                                             0.04 μs/op
	
	
	performance run for u8aToBn (u32) completed with 750,000 iterations.
	
	                  u8aToBn (u32):            37.42 ms
	                                    20,044,409.92 ops/s
	                                             0.05 μs/op
	
	
	performance run for u8aToBn (u64) completed with 750,000 iterations.
	
	                  u8aToBn (u64):            92.27 ms
	                                     8,128,091.53 ops/s
	                                             0.12 μs/op
	
	
	performance run for u8aToBn (u128) completed with 750,000 iterations.
	
	                 u8aToBn (u128):           119.80 ms
	                                     6,260,368.76 ops/s
	                                             0.16 μs/op
	

packages/util/src/u8a/toNumber.spec.ts::

	
	performance run for u8aToNumber (i32) completed with 750,000 iterations.
	
	              u8aToNumber (i32):            22.24 ms
	                                    33,716,073.51 ops/s
	                                             0.03 μs/op
	
	
	performance run for u8aToNumber (u32) completed with 750,000 iterations.
	
	              u8aToNumber (u32):            18.27 ms
	                                    41,054,648.07 ops/s
	                                             0.02 μs/op
	                                             ```

**Comment by peetzweg** [comment]
Closed in favor of #1867

**Comment by peetzweg** [comment]
Closed in favor of https://github.com/polkadot-js/common/pull/1867

**Pull request closed without merging**
