### PR TITLE
add ledger configs for encointer and integritee

### PR DESCRIPTION
**Pull request by brenzi**
Encointer: shares derivation with Kusama as it is a teleporter systemchain

Integritee: New slip44 registered and derivation path added. Same for our Polkadot and Kusama parachains as the token is the same TEER (about to be bridged)

* [x] await merge of https://github.com/satoshilabs/slips/pull/1785

### CODE REVIEW

**Review by TarikGul — DISMISSED** [review]

**Comment by TarikGul** [comment]
Looks like there is a general issue around the coupling of the hw-ledger lib, with the network defaults. I am on the fence about things but now that the generic app exists, I am in the boat that these tests either: a) need to change, or b) there needs to be some rework done. It really becomes a pita for new chains that want to onboard their chains to use ledger in apps.

**Comment by brenzi** [comment]
pita indeed.
* [ ] https://github.com/Zondax/ledger-substrate-js/pull/134

will submit integritee as well

**Comment by brenzi** [comment]
@TarikGul It seems the above PR's aren't necessary according to zondax becasue we will use the generic app. May I ask you to adjust the CI tests accordingly?

https://github.com/Zondax/ledger-substrate-js/pull/134#issuecomment-2341553093

**Comment by TarikGul** [comment]
Yea, I'll work on cleaning that up today for you!

**Comment by TarikGul** [comment]
To make things easier I wrote a replacement PR to avoid all the linter and test errors: https://github.com/polkadot-js/common/pull/1939 - It is a extension of you PR :), Thanks again for your patience

**Comment by TarikGul** [comment]
I'll make sure to release this and get this part of the release cycle next week so it can make it to the extension etc.

**Comment by TarikGul** [comment]
Closing in favor of: https://github.com/polkadot-js/common/pull/1939

**Pull request closed without merging**
