### PR TITLE
Add Ternoa for ledger hardware support

### PR DESCRIPTION
**Pull request by mohsinriaz17**
This PR is part of the process to enable Ledger hardware wallet support on Ternoa network  

A forked version of polka-app with ledger support enabled 
https://cloudflare-ipfs.com/ipfs/QmZqxLqiLfhePSrKsUJNkKP1QXx7kg5iMCKDrHwCJxB2Di/?rpc=wss%3A%2F%2Fmainnet.ternoa.network#/settings 

conjugate PRs for enabling Ledger Hardware wallet support 
Slips: https://github.com/satoshilabs/slips/pull/1398 (merged)  
Zondax: https://github.com/Zondax/ledger-substrate-js/pull/85   
Paritytech: https://github.com/paritytech/ss58-registry/pull/155

### CODE REVIEW

**Review by jacogr — CHANGES_REQUESTED** [review]
Some linting failures on CI. This just all seem to be related to the key ordering (it expects it alphabetical).

https://github.com/polkadot-js/common/actions/runs/3965947790/jobs/6799658273#step:4:59

**Comment by jacogr** [comment]
Seems all ok - CI checks will now pass when it is available in the `@zondax/ledger-substrate` package. (i.e. when it is merged there)

**Comment by jacogr** [comment]
If you merge in master it should make CI happy.

**Comment by mohsinriaz17** [comment]
> If you merge in master it should make CI happy.

Hello @jacogr,
the https://www.npmjs.com/package/@zondax/ledger-substrate/v/0.40.4 is published and includes "ternoa"
can you trigger the CI check again please, it will be happy :)

Screenshot 2023-01-25 at 2 20 21 PM

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/common/blob/01839b5f63638bda466bb1513cc63184451c3cd5/packages/hw-ledger/package.json#L29 - it is in master, hence asking to merge in the master branch.

**Comment by mohsinriaz17** [comment]
got it, thanks for the explanation
It is added with PR: https://github.com/polkadot-js/common/pull/1715

i will wait for CI

Thanks much

**Comment by jacogr** [comment]
You will still need to make a commit to merge master into this branch (i.e. `mohsinriaz17:master`) before I can trigger CI.

**Review by jacogr — APPROVED** [review]

**Pull request merged**
