### PR TITLE
Add missing dependencies to util-crypto

### PR DESCRIPTION
**Pull request by Stefie**
Util-crypto currently breaks the JS API because `bs58` is being imported but missing in the dependencies and therefore not installed.

### CODE REVIEW

**Comment by jacogr** [comment]
https://github.com/polkadot-js/common/blob/master/yarn.lock#L1870
https://github.com/polkadot-js/common/blob/master/yarn.lock#L3167

**Comment by jacogr** [comment]
The correct fix is moving it from `@polkadot/keyring` to `@polkadot/util-crypto`

**Comment by Stefie** [comment]
I didn't check the other packages for unused imports. I removed it from `keyring` now

**Comment by Stefie** [comment]
GitHub notification test for @shawntabrizi

**Pull request merged**
