### PR TITLE
Add Enjin & Matrixchain to list of network that support ledger

### PR DESCRIPTION
**Pull request by leonardocustodio**

### CODE REVIEW

**Comment by leonardocustodio** [comment]
We've just got it merged on Ledger App Database, @jacogr please let me know if you require any changes.
Regards,

**Comment by jacogr** [comment]
CI is failing, so not mergable yet - https://github.com/polkadot-js/common/actions/runs/6133296168/job/16764139862?pr=1879#step:5:89

We probably would need to pull in the latest `@zondax/ledger-substrate` package before that would pass.

**Review by jacogr — CHANGES_REQUESTED** [review]
CI is failing, so not mergable yet - https://github.com/polkadot-js/common/actions/runs/6133296168/job/16764139862?pr=1879#step:5:89

We probably would need to pull in the latest @zondax/ledger-substrate package before that would pass.

**Comment by leonardocustodio** [comment]
Hello, I've pulled the latest updates and I believe it should pass now.

**Review by jacogr — CHANGES_REQUESTED** [review]
Could you please just merge in master, aka after this where all the dev deps were bumped - https://github.com/polkadot-js/common/pull/1880

**Comment by leonardocustodio** [comment]
Yes, just rebased it on master

**Review by jacogr — APPROVED** [review]

**Pull request merged**
