### PR TITLE
Reserving 65 for Aventus based on the new extended range

### PR DESCRIPTION
**Pull request by nahuseyoum**

### CODE REVIEW

**Comment by jacogr** [comment]
Not ignoring it, CI here monitors Substrate master as well, so when merged there will merge/align on this side.

**Comment by nahuseyoum** [comment]
@jacogr The companion PR has been merged on substrate, can you please rerun the CI checks?

**Comment by jacogr** [comment]
It will still fail, since a couple has been merged. I will add the others in the morning (after CI logs an issue) and then merge this.

**Review by jacogr — APPROVED** [review]

**Comment by jacogr** [comment]
Addresses part of #878

**Pull request merged**
