### PR TITLE
Add Dock network id for address generation

### PR DESCRIPTION
**Pull request by lovesh**
Taking 21 and 22 for testnet and mainnet

Signed-off-by: lovesh <lovesh.bond@gmail.com>

### CODE REVIEW

**Comment by jacogr** [comment]
Can we just make sure it is includes in substrate, i.e. https://github.com/paritytech/substrate/blob/master/primitives/core/src/crypto.rs#L405

(The J/S area is lagging behind there, so it misses a couple - but just want to ensure we don't make "new rules" here)

**Comment by lovesh** [comment]
> a

Sorry for the late reply. Yes, its here https://github.com/paritytech/substrate/pull/6714.

**Comment by jacogr** [comment]
Perfect, happy to merge this once the above is in - so will keep an eye.

**Comment by lovesh** [comment]
@jacogr The Substrate PR is merged now.

**Review by jacogr — APPROVED** [review]

**Pull request merged**
