### PR TITLE
Add peaq support for ledger

### PR DESCRIPTION
**Pull request by lavish0000**
add ledger support for peaq

peaq is listed in - 

BIP-0044 - https://github.com/satoshilabs/slips/blob/master/slip-0044.md
ledger-substrate-js - https://github.com/Zondax/ledger-substrate-js/pull/115

### CODE REVIEW

**Comment by lavish0000** [comment]
@jacogr , Can you please review this?

**Review by TarikGul — APPROVED** [review]

**Comment by TarikGul** [comment]
This will be out in 13.0.2 shortly

**Comment by lavish0000** [comment]
Thank you so much, @TarikGul.

I have another question: When will the ledger icon appear on the Polkadot.js app for peaq or within our network in the Polkadot.js extension list of ledger devices?

Additionally, do we need to make any changes in other Polkadot.js repositories to add ledger support?

**Comment by TarikGul** [comment]
> Additionally, do we need to make any changes in other Polkadot.js repositories to add ledger support?

As long as you have a running chain is Polkadot.js this is all that is required (I am almost positive, and will let you know otherwise).

> When will the ledger icon appear on the Polkadot.js app for peaq or in the Polkadot.js extension list of networks that support ledger devices?

For apps, and the extension it should be the same but its based off of if it identifies the chain as `havingLedgerSupport` which is enabled based on the configs you passed in in this PR. So you should be alright.

**Comment by TarikGul** [comment]
Ledger in apps is going to be fixed first this week with the new updates and then the extension. We have to update the interface for how the extension interacts with dApps since it now requires retrieving the metadata blob for constructing the proof to attach to the tx for signing. So you will see incoming PR's to have all this fixed soon.

**Comment by lavish0000** [comment]
Thanks for clarifying, @TarikGul 

I'm asking because I'm unable to see the ledger icon in Polkadot.js apps and extensions. I ran the Polkadot.js apps locally and found that the issue is due to "@polkadot/networks" needing to be updated to version 13.0.2 for it to work. 
So basically dependency update is needed.

Do you know how dependency update is usually handled? Does the Polkadot team update it periodically, or do I need to create a pull request (PR) for this?

**Comment by TarikGul** [comment]
> Thanks for clarifying, @TarikGul
> 
> I'm asking because I'm unable to see the ledger icon in Polkadot.js apps and extensions. I ran the Polkadot.js apps locally and found that the issue is due to "@polkadot/networks" needing to be updated to version 13.0.2 for it to work. So basically dependency update is needed.
> 
> Do you know how dependency update is usually handled? Does the Polkadot team update it periodically, or do I need to create a pull request (PR) for this?

I am actually the one who does all the downstream updates. Everything but apps will be updated by Monday then we will update the common deps in apps during the week, but it also requires a large rework of the Ledger interface in apps, so it wont be immediate. 

The release Process is not as straightforward as updating the deps in one place unfortunately everything has layers in PJS - meaning things have to be updated in there tree order: wasm -> common -> api -> phishing -> tools -> ui -> extension -> apps

So it takes a few days to get everything updated tested etc. And in this case because 13.0.2 is going to be a huge change for apps it will take an extra day or so.

**Pull request merged**
